### ISSUE TITLE
load specific modules, not the 'dot' namespace

### ISSUE THREAD

**Issue by pixelzoom** [alecmartin/quantum-bound-states#11]
In several places you have something like this (e.g. PoentialWell.js):

``` js
var dot = require( 'DOT/dot' );
//...
var FastArray = dot.FastArray;
```

Don't load the 'dot' namespace. Instead, load the individual modules that you need.  In the above case, this becomes:

``` js
var FastArray = require( 'DOT/FastArray' );
```

**Comment by pixelzoom** [comment]
Ah, I see... There is no 'DOT/FastArray'.  @jonathanolson, can you please advise here?  Perhaps use this?:

``` js
var FastArray = require( 'DOT/dot' ).FastArray;
```

**Comment by EmberRandall** [comment]
The simulation Energy-Skate-Park-Basics does it the way I was doing it (I copied it from there), if that helps

**Comment by jonathanolson** [comment]
For now, that's probably the best pattern:

``` js
var FastArray = require( 'DOT/dot' ).FastArray;
```

Should I add DOT/FastArray so it can be imported directly? It was meant mostly for internal use.

**Comment by EmberRandall** [comment]
This sim needs very large arrays, and it looked like FastArray created those in an efficient manner.  Since Energy-Skate-Park-Basics was using it for its large sets of data, I figured that was the best way.  Is there a better way to make big arrays of a certain length?

**Comment by jonathanolson** [comment]
Since we've dropped support for IE9, presumably you could just use window.Float64Array directly (IE9 doesn't support Float64Array).
