### ISSUE TITLE
temporary file checked into GitHub

### ISSUE THREAD

**Issue by pixelzoom** [alecmartin/quantum-bound-states#13]
js/quantum-bound-states/view/.EnergyLine.js.swp looks like a temporary file created by an editor.  It should be deleted.  If your editor frequently creates these files, you may want to add an entry to .gitignore so that temporary files are ignored by git: `*.swp`

**Comment by EmberRandall** [comment]
I deleted it; guys, please make sure you're not committing these files!

**Comment by pixelzoom** [comment]
Did you add `*.swp` to .gitignore?
