### ISSUE TITLE
move duplicated code to supertype

### ISSUE THREAD

**Issue by pixelzoom** [alecmartin/quantum-bound-states#27]
All subtypes of PotentialWell duplicate these 2 lines of code:

``` js
this.wellOffsetProperty = new Property( wellOffset );
this.wellOffsetProperty.link( thisNode.redrawEigenstates );
```

Since this is common to all subtypes, it should be moved to the supertype.

**Comment by pixelzoom** [comment]
I don't see a commit associated with this issue. Did you fix it before closing it?

**Comment by EmberRandall** [comment]
Yes, it got fixed when I was decoupling the model

**Comment by pixelzoom** [comment]
While working on #28, I noticed some additional things that are duplicated in subtypes: `this.minEnergy, this.maxEnergy, this.groundState`.  These should be passed in to PotentialWell constructor.  Especially true for this.groundState, since it's used in redrawEigenstates, which we be called when you link to it in PotentialWells. In the current implementation, this.groundState won't exist when the PotentialWell constructor is called.
