### ISSUE TITLE
ordering dependency for potentials (instances, names, images)

### ISSUE THREAD

**Issue by pixelzoom** [alecmartin/quantum-bound-states#30]
Here's the offending code:

``` js
// QuantumBoundStatesModel
this.potentials = [squareWell, asymWell, coulomb1D, coulomb3D, oscillatorWell];

// PotentialComboBox
var potentialNames = [squareString, asymString, coulomb1DString, coulomb3DString, harmonicString];
var images = [squareImage, asymImage, coulombImage, coulombImage, harmonicImage];
```

There's an ordering dependency here between 3 different arrays, in 2 different files. If any one of them gets out of order, things will go badly.  This type of ordering dependency is to be avoided in general.

One way to fix this would be to add 'name' and 'image' fields to PotentialWell, and set the name and image in the constructors for PotentialWell subtypes.

**Comment by pixelzoom** [comment]
Reopening (highly recommended to have me review these before closing).

The way you've done this is problematic. Example:

``` js
  function SquareWellPotential( minX, maxX, particle, wellOffset, wellWidth, wellHeight ) {
    // strings
    var squareString = require( 'string!QUANTUM_BOUND_STATES/square' );
    // images
    var squareImage = require( 'image!QUANTUM_BOUND_STATES/SquareIcon.png' );
...
}
```

`require` statements should be outside of the constructor. You don't need a copy of the string and image for each instance of SquareWellPotential. I'll check in a fix to SquareWellPotential, you can do the others.

**Comment by pixelzoom** [comment]
Getting closer, but still not quite there. I pushed changes to PotentialComboBox in the above commits.  Have a look, let me know if you have any questions.

**Comment by EmberRandall** [comment]
Okay that makes sense, thanks!
