### ISSUE TITLE
images/license.txt is empty

### ISSUE THREAD

**Issue by pixelzoom** [alecmartin/quantum-bound-states#6]
images/license.txt should describe the licensing for all images files in that directory. See https://github.com/phetsims/simula-rasa/blob/master/images/README.txt for a description of the files format. See other sims for examples.

**Comment by EmberRandall** [comment]
I think I fixed it, does it look alright now?

**Comment by pixelzoom** [comment]
@EmilyRandall I'll have a look tomorrow.  But when you make a change/fix related to an issue, it's customary to put the issue number in the commit message (e.g., "#6 add entries to license.txt). Doing so causes the commit to appear in the issue, where the reviewer can click on it to view a diff.

**Comment by pixelzoom** [comment]
Incorrect. You've used `Author=Emily Randall`. The format description indicates `author` in lowercase.

**Comment by EmberRandall** [comment]
Ok, I fixed that (unfortunately before reading the comment above it, I'll make sure the commits have the issue number in the future)
